import math

print(math.pi)
print(math.e)
print(math.sqrt(16))
print(math.factorial(5))
print(math.pow(2, 3))
print(math.floor(3.7))
print(math.ceil(3.7))
print(math.sin(math.pi / 2))
print(math.cos(0))
print(math.tan(math.pi / 4))
print(math.log(100, 10))
print(math.log2(256))   
print(math.log10(1000))
print(math.radians(180))